name: Spotify Badge

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Spotify profile
        uses: kittinan/spotify-github-profile@v1.0.0
        with:
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
